# Generated by Django 6.0.4 on 2026-05-05 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_email', models.EmailField(max_length=254)),
                ('code_hash', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'codigo de acesso',
                'verbose_name_plural': 'codigos de acesso',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=150, verbose_name='nome de exibicao')),
                ('institutional_id', models.CharField(blank=True, max_length=30, verbose_name='matricula ou SIAPE')),
                ('is_student', models.BooleanField(default=False, verbose_name='aluno')),
                ('is_professor', models.BooleanField(default=False, verbose_name='professor')),
                ('is_technician', models.BooleanField(default=False, verbose_name='tecnico administrativo')),
                ('is_department_head', models.BooleanField(default=False, verbose_name='chefe de departamento')),
                ('is_course_coordinator', models.BooleanField(default=False, verbose_name='coordenador de curso')),
                ('is_internship_coordinator', models.BooleanField(default=False, verbose_name='coordenador de estagio')),
                ('is_tcc1_coordinator', models.BooleanField(default=False, verbose_name='coordenador de TCC 1')),
                ('is_tcc2_coordinator', models.BooleanField(default=False, verbose_name='coordenador de TCC 2')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
            },
        ),
    ]
