# Generated by Django 6.0.4 on 2026-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accessinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessinvitation',
            name='expires_at',
            field=models.DateTimeField(verbose_name='expira em'),
        ),
    ]
