# Generated by Django 6.0.4 on 2026-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accessinvitation_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_manage_landing_page',
            field=models.BooleanField(default=False, verbose_name='pode gerenciar landing page'),
        ),
    ]
