# Generated by Codex on 2026-05-28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_profile_can_manage_landing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessinvitation",
            name="is_student",
            field=models.BooleanField(default=False, verbose_name="aluno"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_professor",
            field=models.BooleanField(default=False, verbose_name="professor"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_technician",
            field=models.BooleanField(default=False, verbose_name="tecnico administrativo"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_department_head",
            field=models.BooleanField(default=False, verbose_name="chefe de departamento"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_course_coordinator",
            field=models.BooleanField(default=False, verbose_name="coordenador de curso"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_internship_coordinator",
            field=models.BooleanField(default=False, verbose_name="coordenador de estagio"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_tcc1_coordinator",
            field=models.BooleanField(default=False, verbose_name="coordenador de TCC 1"),
        ),
        migrations.AddField(
            model_name="accessinvitation",
            name="is_tcc2_coordinator",
            field=models.BooleanField(default=False, verbose_name="coordenador de TCC 2"),
        ),
    ]
