# Generated by Django 6.0.4 on 2026-05-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge', models.CharField(max_length=120, verbose_name='selo do topo')),
                ('hero_title', models.CharField(max_length=220, verbose_name='titulo principal')),
                ('hero_description', models.TextField(verbose_name='descricao principal')),
                ('hero_primary_cta_label', models.CharField(default='Consultar servicos', max_length=60, verbose_name='texto do botao principal')),
                ('hero_secondary_cta_label', models.CharField(default='Area do usuario', max_length=60, verbose_name='texto do botao secundario')),
                ('access_badge', models.CharField(max_length=120, verbose_name='selo do bloco de acesso')),
                ('access_title', models.CharField(max_length=180, verbose_name='titulo do bloco de acesso')),
                ('access_description', models.TextField(verbose_name='descricao do bloco de acesso')),
                ('access_cta_label', models.CharField(default='Abrir area do usuario', max_length=60, verbose_name='texto do botao de acesso')),
                ('services_badge', models.CharField(max_length=120, verbose_name='selo da secao de servicos')),
                ('services_title', models.CharField(max_length=180, verbose_name='titulo da secao de servicos')),
                ('services_description', models.TextField(verbose_name='descricao da secao de servicos')),
                ('modules_badge', models.CharField(max_length=120, verbose_name='selo da secao autenticada')),
                ('modules_title', models.CharField(max_length=180, verbose_name='titulo da secao autenticada')),
                ('modules_description', models.TextField(verbose_name='descricao da secao autenticada')),
                ('contact_badge', models.CharField(max_length=120, verbose_name='selo da secao final')),
                ('contact_title', models.CharField(max_length=180, verbose_name='titulo da secao final')),
                ('contact_description', models.TextField(verbose_name='descricao da secao final')),
                ('contact_panel_badge', models.CharField(max_length=120, verbose_name='selo do painel lateral final')),
                ('contact_panel_description', models.TextField(verbose_name='descricao do painel lateral final')),
                ('contact_cta_label', models.CharField(default='Abrir area do usuario', max_length=60, verbose_name='texto do botao final')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuracao da landing page',
                'verbose_name_plural': 'configuracoes da landing page',
            },
        ),
        migrations.CreateModel(
            name='LandingSectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero_metric', 'Metricas do topo'), ('access_step', 'Etapas de acesso'), ('service', 'Cartoes de servicos'), ('module_point', 'Destaques da area autenticada'), ('audience_card', 'Cartoes de perfis')], max_length=30, verbose_name='secao')),
                ('label', models.CharField(blank=True, max_length=80, verbose_name='rotulo')),
                ('title', models.CharField(max_length=180, verbose_name='titulo')),
                ('description', models.TextField(blank=True, verbose_name='descricao')),
                ('action_label', models.CharField(blank=True, max_length=60, verbose_name='texto do link')),
                ('action_url', models.CharField(blank=True, max_length=255, verbose_name='URL do link')),
                ('order', models.PositiveSmallIntegerField(default=10, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.landingpagecontent')),
            ],
            options={
                'verbose_name': 'item da landing page',
                'verbose_name_plural': 'itens da landing page',
                'ordering': ('section', 'order', 'pk'),
            },
        ),
    ]
