# Generated by Django 6.0.4 on 2026-05-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagecontent',
            name='access_badge',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='selo do bloco de acesso'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='access_cta_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='texto do botao de acesso'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='access_description',
            field=models.TextField(blank=True, default='', verbose_name='descricao do bloco de acesso'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='access_title',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='titulo do bloco de acesso'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_badge',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='selo da secao final'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_cta_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='texto do botao final'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_description',
            field=models.TextField(blank=True, default='', verbose_name='descricao da secao final'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_panel_badge',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='selo do painel lateral final'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_panel_description',
            field=models.TextField(blank=True, default='', verbose_name='descricao do painel lateral final'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='contact_title',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='titulo da secao final'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_badge',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='selo do topo'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_description',
            field=models.TextField(blank=True, default='', verbose_name='descricao principal'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_primary_cta_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='texto do botao principal'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_secondary_cta_label',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='texto do botao secundario'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='hero_title',
            field=models.CharField(blank=True, default='', max_length=220, verbose_name='titulo principal'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='modules_badge',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='selo da secao autenticada'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='modules_description',
            field=models.TextField(blank=True, default='', verbose_name='descricao da secao autenticada'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='modules_title',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='titulo da secao autenticada'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='services_badge',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='selo da secao de servicos'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='services_description',
            field=models.TextField(blank=True, default='', verbose_name='descricao da secao de servicos'),
        ),
        migrations.AlterField(
            model_name='landingpagecontent',
            name='services_title',
            field=models.CharField(blank=True, default='', max_length=180, verbose_name='titulo da secao de servicos'),
        ),
    ]
